import { useState, useEffect, useCallback, useMemo } from 'react';
import { useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { PlaylistTrack, Track } from '../../types';
import {
  getPlaylist,
  generatePlaylist,
  publishPlaylist,
} from '../../api/playlists';
import { useAutoSave } from '../../hooks/useAutoSave';
import type { GenerationConfig } from '../../hooks/useAutoSave';
import { usePlayer } from '../../context/PlayerContext';
import { useAuth } from '../../context/AuthContext';
import PlaylistHeader from './PlaylistHeader';
import PlaylistTrackList from './PlaylistTrackList';
import RegenerateButton from './RegenerateButton';
import NostalgicArtistsEditor from './NostalgicArtistsEditor';
import PlaylistConfig from './PlaylistConfig';
import SearchBar from '../search/SearchBar';
import LoadingSpinner from '../common/LoadingSpinner';

function recalculatePositions(tracks: PlaylistTrack[]): PlaylistTrack[] {
  return tracks.map((track, index) => ({ ...track, position: index }));
}

export default function PlaylistEditor() {
  const { id } = useParams<{ id: string }>();
  const playlistId = id ? Number(id) : undefined;
  const queryClient = useQueryClient();
  const { playTrack } = usePlayer();
  const { user } = useAuth();

  const { data: playlist, isLoading } = useQuery({
    queryKey: ['playlist', playlistId],
    queryFn: () => getPlaylist(playlistId!),
    enabled: !!playlistId,
  });

  const [name, setName] = useState('');
  const [tracks, setTracks] = useState<PlaylistTrack[]>([]);
  const [lockedTrackIds, setLockedTrackIds] = useState<Set<string>>(new Set());

  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [generationConfig, setGenerationConfig] = useState<GenerationConfig>({
    favoritesRatio: 0.3,
    discoveryRatio: 0.3,
    eraHitsRatio: 0.4,
    targetSongCount: 125,
  });

  // Only hydrate local state when navigating to a different playlist,
  // not on every refetch (which would clobber unsaved state).
  useEffect(() => {
    if (!playlist) return;
    setName(playlist.name);
    setTracks(playlist.tracks);
    setLockedTrackIds(
      new Set(playlist.tracks.filter((t) => t.locked).map((t) => t.id))
    );
    setGenerationConfig({
      favoritesRatio: playlist.favoritesRatio,
      discoveryRatio: playlist.discoveryRatio,
      eraHitsRatio: playlist.eraHitsRatio,
      targetSongCount: playlist.targetSongCount,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [playlist?.id]);


  const [birthYearInput, setBirthYearInput] = useState<string>(
    String(playlist?.birthYear ?? user?.birthYear ?? 1991)
  );
  const birthYear = parseInt(birthYearInput, 10) || 0;

  useEffect(() => {
    if (playlist?.birthYear) setBirthYearInput(String(playlist.birthYear));
  }, [playlist?.birthYear]);

  const stableConfig = useMemo(() => generationConfig, [
    generationConfig.favoritesRatio,
    generationConfig.discoveryRatio,
    generationConfig.eraHitsRatio,
    generationConfig.targetSongCount,
  ]);

  const { isSaving, justSaved } = useAutoSave(playlistId, name, tracks, birthYear, stableConfig);

  const generateMutation = useMutation({
    mutationFn: () =>
      generatePlaylist(playlistId!, {
        birthYear,
        lockedTrackIds: [...lockedTrackIds],
      }),
    onSuccess: (result) => {
      const lockedTracks = tracks.filter((t) => lockedTrackIds.has(t.id));
      const newTracks = result.tracks.filter(
        (t) => !lockedTrackIds.has(t.id)
      );

      const merged: PlaylistTrack[] = [];
      let newIdx = 0;

      for (let i = 0; i < result.tracks.length; i++) {
        const lockedAtPos = lockedTracks.find((t) => t.position === i);
        if (lockedAtPos) {
          merged.push(lockedAtPos);
        } else if (newIdx < newTracks.length) {
          merged.push(newTracks[newIdx++]);
        }
      }

      while (newIdx < newTracks.length) {
        merged.push(newTracks[newIdx++]);
      }

      setTracks(recalculatePositions(merged));
    },
  });

  // Auto-generate on first load if playlist is empty
  useEffect(() => {
    if (playlist && playlist.tracks.length === 0 && playlistId && !hasAutoGenerated && !generateMutation.isPending) {
      setHasAutoGenerated(true);
      generateMutation.mutate();
    }
  }, [playlist, playlistId, hasAutoGenerated]);

  const [justPublished, setJustPublished] = useState(false);

  const publishMutation = useMutation({
    mutationFn: () => publishPlaylist(playlistId!),
    onSuccess: () => {
      setJustPublished(true);
      queryClient.invalidateQueries({ queryKey: ['playlist', playlistId] });
      setTimeout(() => setJustPublished(false), 10000);
    },
  });

  const handleReorder = useCallback(
    (startIndex: number, endIndex: number) => {
      setTracks((prev) => {
        const updated = [...prev];
        const [moved] = updated.splice(startIndex, 1);
        updated.splice(endIndex, 0, moved);
        return recalculatePositions(updated);
      });
    },
    []
  );

  const handleMove = useCallback(
    (trackId: string, newPosition: number) => {
      setTracks((prev) => {
        const currentIndex = prev.findIndex((t) => t.id === trackId);
        if (currentIndex === -1) return prev;
        const clampedTarget = Math.max(
          0,
          Math.min(newPosition, prev.length - 1)
        );
        if (clampedTarget === currentIndex) return prev;

        const updated = [...prev];
        const [moved] = updated.splice(currentIndex, 1);
        updated.splice(clampedTarget, 0, moved);
        return recalculatePositions(updated);
      });
    },
    []
  );

  const handleToggleLock = useCallback((trackId: string) => {
    setLockedTrackIds((prev) => {
      const next = new Set(prev);
      if (next.has(trackId)) {
        next.delete(trackId);
      } else {
        next.add(trackId);
      }
      return next;
    });

    setTracks((prev) =>
      prev.map((t) =>
        t.id === trackId ? { ...t, locked: !t.locked } : t
      )
    );
  }, []);

  const handleLockAll = useCallback(() => {
    setLockedTrackIds(new Set(tracks.map((t) => t.id)));
    setTracks((prev) => prev.map((t) => ({ ...t, locked: true })));
  }, [tracks]);

  const handleUnlockAll = useCallback(() => {
    setLockedTrackIds(new Set());
    setTracks((prev) => prev.map((t) => ({ ...t, locked: false })));
  }, []);

  const handleShuffle = useCallback(() => {
    setTracks((prev) => {
      const locked = prev.filter((t) => lockedTrackIds.has(t.id));
      const unlocked = prev.filter((t) => !lockedTrackIds.has(t.id));

      // Fisher-Yates shuffle on unlocked tracks
      for (let i = unlocked.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [unlocked[i], unlocked[j]] = [unlocked[j], unlocked[i]];
      }

      // Merge: locked stay at their positions, unlocked fill the rest
      const result: PlaylistTrack[] = new Array(prev.length);
      locked.forEach((t) => { result[t.position] = t; });

      let unlockIdx = 0;
      for (let i = 0; i < result.length; i++) {
        if (!result[i]) {
          result[i] = unlocked[unlockIdx++];
        }
      }

      return recalculatePositions(result);
    });
  }, [lockedTrackIds]);

  const handleRemove = useCallback((trackId: string) => {
    setTracks((prev) =>
      recalculatePositions(prev.filter((t) => t.id !== trackId))
    );
    setLockedTrackIds((prev) => {
      const next = new Set(prev);
      next.delete(trackId);
      return next;
    });
  }, []);

  const handleAddTrack = useCallback((track: Track) => {
    setTracks((prev) => {
      const newTrack: PlaylistTrack = {
        ...track,
        position: prev.length,
        locked: false,
        source: 'manual',
      };
      return [...prev, newTrack];
    });
  }, []);

  if (isLoading) return <LoadingSpinner />;

  return (
    <div className="pb-24">
      <PlaylistHeader
        name={name}
        onNameChange={setName}
        tracks={tracks}
        isSaving={isSaving}
        justSaved={justSaved}
        onPublish={() => publishMutation.mutate()}
        isPublishing={publishMutation.isPending}
        spotifyPlaylistId={playlist?.spotifyPlaylistId}
        justPublished={justPublished}
      />

      <div className="mb-6 flex items-center gap-4">
        <label className="flex items-center gap-2 text-sm text-[#b3b3b3]">
          Birth Year
          <input
            type="text"
            inputMode="numeric"
            value={birthYearInput}
            onChange={(e) => {
              const val = e.target.value.replace(/\D/g, '').slice(0, 4);
              setBirthYearInput(val);
            }}
            className="w-20 rounded-lg bg-[#282828] px-3 py-2 text-sm text-white outline-none focus:ring-1 focus:ring-[#1DB954]"
          />
        </label>

        <RegenerateButton
          tracks={tracks}
          lockedTrackIds={lockedTrackIds}
          isGenerating={generateMutation.isPending}
          onRegenerate={() => generateMutation.mutate()}
          onLockAll={handleLockAll}
          onUnlockAll={handleUnlockAll}
          onShuffle={handleShuffle}
        />
      </div>

      <PlaylistConfig config={generationConfig} onChange={setGenerationConfig} />

      <NostalgicArtistsEditor />

      <SearchBar onAddTrack={handleAddTrack} />

      <PlaylistTrackList
        tracks={tracks}
        onReorder={handleReorder}
        onPlay={playTrack}
        onToggleLock={handleToggleLock}
        onRemove={handleRemove}
        onMove={handleMove}
        isGenerating={generateMutation.isPending}
      />
    </div>
  );
}
