import { useState, useEffect, useCallback } from 'react';
import { useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { PlaylistTrack, Track } from '../../types';
import {
  getPlaylist,
  generatePlaylist,
  publishPlaylist,
} from '../../api/playlists';
import { useAutoSave } from '../../hooks/useAutoSave';
import { usePlayer } from '../../context/PlayerContext';
import PlaylistHeader from './PlaylistHeader';
import PlaylistTrackList from './PlaylistTrackList';
import RegenerateButton from './RegenerateButton';
import NostalgicArtistsEditor from './NostalgicArtistsEditor';
import SearchBar from '../search/SearchBar';
import LoadingSpinner from '../common/LoadingSpinner';

function recalculatePositions(tracks: PlaylistTrack[]): PlaylistTrack[] {
  return tracks.map((track, index) => ({ ...track, position: index }));
}

export default function PlaylistEditor() {
  const { id } = useParams<{ id: string }>();
  const playlistId = id ? Number(id) : undefined;
  const queryClient = useQueryClient();
  const { playTrack } = usePlayer();

  const { data: playlist, isLoading } = useQuery({
    queryKey: ['playlist', playlistId],
    queryFn: () => getPlaylist(playlistId!),
    enabled: !!playlistId,
  });

  const [name, setName] = useState('');
  const [tracks, setTracks] = useState<PlaylistTrack[]>([]);
  const [lockedTrackIds, setLockedTrackIds] = useState<Set<string>>(new Set());

  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  useEffect(() => {
    if (!playlist) return;
    setName(playlist.name);
    setTracks(playlist.tracks);
    setLockedTrackIds(
      new Set(playlist.tracks.filter((t) => t.locked).map((t) => t.id))
    );
  }, [playlist]);


  const { isSaving, justSaved } = useAutoSave(playlistId, name, tracks);

  const [birthYear, setBirthYear] = useState<number>(
    playlist?.birthYear ?? 1991
  );

  useEffect(() => {
    if (playlist?.birthYear) setBirthYear(playlist.birthYear);
  }, [playlist?.birthYear]);

  const generateMutation = useMutation({
    mutationFn: () =>
      generatePlaylist(playlistId!, {
        birthYear,
        lockedTrackIds: [...lockedTrackIds],
      }),
    onSuccess: (result) => {
      const lockedTracks = tracks.filter((t) => lockedTrackIds.has(t.id));
      const newTracks = result.tracks.filter(
        (t) => !lockedTrackIds.has(t.id)
      );

      const merged: PlaylistTrack[] = [];
      let newIdx = 0;

      for (let i = 0; i < result.tracks.length; i++) {
        const lockedAtPos = lockedTracks.find((t) => t.position === i);
        if (lockedAtPos) {
          merged.push(lockedAtPos);
        } else if (newIdx < newTracks.length) {
          merged.push(newTracks[newIdx++]);
        }
      }

      while (newIdx < newTracks.length) {
        merged.push(newTracks[newIdx++]);
      }

      setTracks(recalculatePositions(merged));
      queryClient.invalidateQueries({ queryKey: ['playlist', playlistId] });
    },
  });

  // Auto-generate on first load if playlist is empty
  useEffect(() => {
    if (playlist && playlist.tracks.length === 0 && playlistId && !hasAutoGenerated && !generateMutation.isPending) {
      setHasAutoGenerated(true);
      generateMutation.mutate();
    }
  }, [playlist, playlistId, hasAutoGenerated]);

  const publishMutation = useMutation({
    mutationFn: () => publishPlaylist(playlistId!),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['playlist', playlistId] });
    },
  });

  const handleReorder = useCallback(
    (startIndex: number, endIndex: number) => {
      setTracks((prev) => {
        const updated = [...prev];
        const [moved] = updated.splice(startIndex, 1);
        updated.splice(endIndex, 0, moved);
        return recalculatePositions(updated);
      });
    },
    []
  );

  const handleToggleLock = useCallback((trackId: string) => {
    setLockedTrackIds((prev) => {
      const next = new Set(prev);
      if (next.has(trackId)) {
        next.delete(trackId);
      } else {
        next.add(trackId);
      }
      return next;
    });

    setTracks((prev) =>
      prev.map((t) =>
        t.id === trackId ? { ...t, locked: !t.locked } : t
      )
    );
  }, []);

  const handleRemove = useCallback((trackId: string) => {
    setTracks((prev) =>
      recalculatePositions(prev.filter((t) => t.id !== trackId))
    );
    setLockedTrackIds((prev) => {
      const next = new Set(prev);
      next.delete(trackId);
      return next;
    });
  }, []);

  const handleAddTrack = useCallback((track: Track) => {
    setTracks((prev) => {
      const newTrack: PlaylistTrack = {
        ...track,
        position: prev.length,
        locked: false,
        source: 'manual',
      };
      return [...prev, newTrack];
    });
  }, []);

  if (isLoading) return <LoadingSpinner />;

  return (
    <div className="pb-24">
      <PlaylistHeader
        name={name}
        onNameChange={setName}
        tracks={tracks}
        isSaving={isSaving}
        justSaved={justSaved}
        onPublish={() => publishMutation.mutate()}
        isPublishing={publishMutation.isPending}
      />

      <div className="mb-6 flex items-center gap-4">
        <label className="flex items-center gap-2 text-sm text-[#b3b3b3]">
          Birth Year
          <input
            type="number"
            value={birthYear}
            onChange={(e) => setBirthYear(Number(e.target.value))}
            min={1940}
            max={new Date().getFullYear()}
            className="w-24 rounded-lg bg-[#282828] px-3 py-2 text-sm text-white outline-none focus:ring-1 focus:ring-[#1DB954]"
          />
        </label>

        <RegenerateButton
          tracks={tracks}
          lockedTrackIds={lockedTrackIds}
          isGenerating={generateMutation.isPending}
          onRegenerate={() => generateMutation.mutate()}
        />
      </div>

      <NostalgicArtistsEditor />

      <SearchBar onAddTrack={handleAddTrack} />

      <PlaylistTrackList
        tracks={tracks}
        onReorder={handleReorder}
        onPlay={playTrack}
        onToggleLock={handleToggleLock}
        onRemove={handleRemove}
      />
    </div>
  );
}
